name: Test Missing Item Benchmark

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r missing-item-benchmark/python/requirements.txt

    - name: Run Python missing item benchmark
      run: |
        source venv/bin/activate
        cd missing-item-benchmark/python
        python missing-item.py

    - name: Run unit tests (if any)
      run: |
        source venv/bin/activate
        cd missing-item-benchmark/python
        python -m pytest tests/ -v || echo "No tests found, skipping pytest"
      continue-on-error: true

  test-c:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install C compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Build C benchmark
      run: |
        cd missing-item-benchmark/c
        make clean
        make

    - name: Run C benchmark
      run: |
        cd missing-item-benchmark/c
        make test

    - name: Test debug build
      run: |
        cd missing-item-benchmark/c
        make debug
        ./missing-item_debug
